services:
  python:
    build:
      context: .
      dockerfile: ./.devcontainer/docker/Dockerfile.mamba
      args:
        ENV_NAME: myenv
    volumes:
      - .:/app
      - conda:/opt/conda
    working_dir: /app

volumes:
  conda:
