services:
  python:
    build:
      context: .
      dockerfile: ./docker/development/python/Dockerfile
      args:
        ENV_NAME: myenv
    volumes:
      - .:/app
      - conda:/opt/conda
    working_dir: /app

volumes:
  conda:
